personal_info:
  first_name: "Harry"
  last_name: "Potter"
  national_id_number: "80.07.31-XXX.XX"
  address_line_1: "Chaussée de Howgarts 62"
  address_line_2: "1040 Brussels"
  city_for_signature: "Brussels"